// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260613123623_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DownloadedSong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("NetworkId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OriginId")
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SongId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("NetworkId");

                    b.HasIndex("SongId")
                        .IsUnique();

                    b.ToTable("DownloadedSongs");
                });

            modelBuilder.Entity("NetWork", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Networks");
                });

            modelBuilder.Entity("RequestedSongUser", b =>
                {
                    b.Property<Guid>("RequestedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RequestedSongsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RequestedById", "RequestedSongsId");

                    b.HasIndex("RequestedSongsId");

                    b.ToTable("RequestedSongUser");
                });

            modelBuilder.Entity("Song", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DownloadedSongId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid>("NetworkId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("NetworkId");

                    b.ToTable("Songs", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("SongUser", b =>
                {
                    b.Property<Guid>("CurrentSongsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DownloadedById")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CurrentSongsId", "DownloadedById");

                    b.HasIndex("DownloadedById");

                    b.ToTable("SongUser");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NetworkId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Premium")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PremiumExpirationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NetworkId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RequestedSong", b =>
                {
                    b.HasBaseType("Song");

                    b.ToTable("RequestedSongs", (string)null);
                });

            modelBuilder.Entity("DownloadedSong", b =>
                {
                    b.HasOne("NetWork", "NetWorkNavigation")
                        .WithMany("DownloadedSongs")
                        .HasForeignKey("NetworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Song", "SongNavigation")
                        .WithOne("DownloadedSongNavigation")
                        .HasForeignKey("DownloadedSong", "SongId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("NetWorkNavigation");

                    b.Navigation("SongNavigation");
                });

            modelBuilder.Entity("NetWork", b =>
                {
                    b.HasOne("User", "OwnerNavigation")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OwnerNavigation");
                });

            modelBuilder.Entity("RequestedSongUser", b =>
                {
                    b.HasOne("User", null)
                        .WithMany()
                        .HasForeignKey("RequestedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RequestedSong", null)
                        .WithMany()
                        .HasForeignKey("RequestedSongsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Song", b =>
                {
                    b.HasOne("NetWork", "NetworkNavigation")
                        .WithMany("NetworkSongs")
                        .HasForeignKey("NetworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NetworkNavigation");
                });

            modelBuilder.Entity("SongUser", b =>
                {
                    b.HasOne("Song", null)
                        .WithMany()
                        .HasForeignKey("CurrentSongsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User", null)
                        .WithMany()
                        .HasForeignKey("DownloadedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("User", b =>
                {
                    b.HasOne("NetWork", "NetworkNavigation")
                        .WithMany("Users")
                        .HasForeignKey("NetworkId");

                    b.Navigation("NetworkNavigation");
                });

            modelBuilder.Entity("RequestedSong", b =>
                {
                    b.HasOne("Song", null)
                        .WithOne()
                        .HasForeignKey("RequestedSong", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NetWork", b =>
                {
                    b.Navigation("DownloadedSongs");

                    b.Navigation("NetworkSongs");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Song", b =>
                {
                    b.Navigation("DownloadedSongNavigation");
                });
#pragma warning restore 612, 618
        }
    }
}
